services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: health-next-backend
    env_file:
      - ./Backend/.env
    expose:
      - "4000"
    restart: unless-stopped
    networks:
      - healthnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ""
        VITE_GOOGLE_CLIENT_ID: "208574629204-r4a3afcuqepfuupcj81qn829auvilnn8.apps.googleusercontent.com"
        VITE_RAZORPAY_KEY_ID: "rzp_test_SwAd8QHJDAtPKJ"
    container_name: health-next-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - healthnet

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ""
    container_name: health-next-admin
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - healthnet

networks:
  healthnet:
    driver: bridge